import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NoteAI",
  description: "Generated by Vercel with Bharath's NoteAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
